export const COMPONENT_DEFS = {
  'input':       { inputs: 0, outputs: 1, label: 'Toggle Switch',    category: 'Inputs' },
  'clock':       { inputs: 0, outputs: 1, label: 'Clock Signal',     category: 'Inputs' },
  'buffer':      { inputs: 1, outputs: 1, label: 'Buffer Gate',      category: 'Logic Gates' },
  'not':         { inputs: 1, outputs: 1, label: 'NOT Gate',         category: 'Logic Gates' },
  'and':         { inputs: 2, outputs: 1, label: 'AND Gate',          category: 'Logic Gates' },
  'or':          { inputs: 2, outputs: 1, label: 'OR Gate',           category: 'Logic Gates' },
  'nand':        { inputs: 2, outputs: 1, label: 'NAND Gate',         category: 'Logic Gates' },
  'nor':         { inputs: 2, outputs: 1, label: 'NOR Gate',          category: 'Logic Gates' },
  'xor':         { inputs: 2, outputs: 1, label: 'XOR Gate',          category: 'Logic Gates' },
  'xnor':        { inputs: 2, outputs: 1, label: 'XNOR Gate',         category: 'Logic Gates' },
  'output':      { inputs: 1, outputs: 0, label: 'LED Light',         category: 'Outputs' },
  'rgb-led':     { inputs: 3, outputs: 0, label: 'RGB LED',           category: 'Outputs' },
  'buzzer':      { inputs: 1, outputs: 0, label: 'Buzzer',            category: 'Outputs' },
  'led-bar':    { inputs: 4, outputs: 0, label: 'LED Bar (4-bit)',  category: 'Outputs' },
  'd-flop':      { inputs: 2, outputs: 1, label: 'D Flip-Flop',       category: 'Sequential' },
  'sr-latch':    { inputs: 2, outputs: 2, label: 'SR Latch',          category: 'Sequential' },
  'jk-flop':     { inputs: 3, outputs: 2, label: 'JK Flip-Flop',      category: 'Sequential' },
  't-flop':      { inputs: 2, outputs: 1, label: 'T Flip-Flop',        category: 'Sequential' },
  'half-adder':  { inputs: 2, outputs: 2, label: 'Half Adder',         category: 'Arithmetic' },
  'full-adder':  { inputs: 3, outputs: 2, label: 'Full Adder',         category: 'Arithmetic' },
  'mux-2-1':     { inputs: 3, outputs: 1, label: '2:1 Multiplexer',    category: 'Combinational' },
  'demux-1-2':   { inputs: 2, outputs: 2, label: '1:2 DeMultiplexer',  category: 'Combinational' },
  'decoder-2-4': { inputs: 2, outputs: 4, label: '2:4 Decoder',       category: 'Combinational' },
  'encoder-4-2': { inputs: 4, outputs: 2, label: '4:2 Priority Encoder', category: 'Combinational' },
  'comparator':  { inputs: 4, outputs: 3, label: '2-bit Comparator',  category: 'Combinational' },
  'seven-seg':   { inputs: 4, outputs: 0, label: '7-Seg Display',     category: 'Outputs' },
  'text-label':  { inputs: 0, outputs: 0, label: 'Text Label',        category: 'Utility' },
  'ic-7408':     { inputs: 15, outputs: 15, label: '7408 Quad AND',    category: 'ICs' },
  'ic-7432':     { inputs: 15, outputs: 15, label: '7432 Quad OR',     category: 'ICs' },
  'ic-7404':     { inputs: 15, outputs: 15, label: '7404 Hex NOT',     category: 'ICs' },
  'ic-7400':     { inputs: 15, outputs: 15, label: '7400 Quad NAND',   category: 'ICs' },
  'ic-7402':     { inputs: 15, outputs: 15, label: '7402 Quad NOR',    category: 'ICs' },
  'ic-7486':     { inputs: 15, outputs: 15, label: '7486 Quad XOR',    category: 'ICs' },
};
